# Docker

## Introduction

Nowadays, almost all companies and scientific labs which work with data are also becoming software producers. In some cases, the main reason for this software development is to publish effective scientific work. In other cases, its final aim might be just putting together a set of related functions that work for a similar final objective. However, in both cases, the final software product becomes highly shareable.

This characteristic, the shareability of the software produced, might seem very straightforward but in reality, it can turn into a scaring daunting task to be solved. Why? Because of the heterogeneity of all different platforms, operating systems, dependencies, versioning and so on that our software product makes use of. Please, be aware that prior to its first release, our software product might have been tested in a limited number of PC stations with determined characteristics that can be extremely different from any other potential user's PC station around the world.

All these reasons make [Docker Platform](https://www.docker.com/) really interesting and useful for both software producers and consumers. 

## What is docker?

[Docker](https://www.docker.com/) is a software platform created in 2013 by [Docker, Inc.](https://en.wikipedia.org/wiki/Docker,_Inc.) which its main objective is to *build, share, and run any app anywhere*, independently of the platform and environment where it is executed.

But what does this definition mean? It means that you admiringly can forget about dependencies, libraries, compatibility, etc. to make the app run correctly. To some extent, you could think Docker as a *black box*, as a **snapshot** of the developer's laptop where she or he developt the software you are about to make use of. A snapshot of the precise moment when the developer decided to release the software. Thus, everything you need to run the app is already there, installed and configured inside the Docker object, ready to be used, with no compatibility issues at all.

## Images and containers

Working with Docker, there are two main concepts you are going to hear about constantly: images and containers. An **image** is the virtual file or template that contains the whole set of instructions to build a container. An image is the raw Docker file you will directly download from [Docker Hub](https://hub.docker.com/) developer's repository to your local. On the other hand, a **container** is the executable object directly generated from the image. A container will be the virtual object that represents the snapshot of the app developer's laptop.

In summary, the image is the virtual file that contains the raw instructions to build the executable app, and the executable app is the container itself.

## Docker Hub

[Docker Hub](https://hub.docker.com/) is an online platform that allows creating individual Docker repositories. A Docker repository is a personal account space where you can store one or more versions of the same Docker image, which are represented by tags.

Let us focus on the following image obtained from the [Ubuntu Docker Repository](https://hub.docker.com/_/ubuntu?tab=tags):


## Managing a docker object

## Creating a docker object

## Useful Commands

This page contains a list with some of the most common commands of Docker.
  
  To download a Docker image from Docker Hub:
```console
$ sudo docker push repository/name:tag
```

To run the image *name:tag*. The flag **--rm** indicates to remove the container after stopping the image; whereas the flag **-p** indicates the port on which we want to expose the execution of the image:
```console
$ sudo docker run --rm -p 8500:80 name:tag
```

To list all docker images that are available in our local:
```console
$ sudo docker images
```

To remove the image *image_name*:
```console
$ sudo docker image rm image_name
```

To remove all orphaned images:
```console
$ sudo docker rmi $(sudo docker images -f dangling=true -q)
```

To list all current containers:
```console
$ sudo docker ps
```

To list all stopped containers:
```console
$ sudo docker ps -a 
```

To remove all orphaned containers:
```console
$ sudo docker rm $(sudo docker ps -a -q)
```

To enter inside a container in execution:
```console
$ sudo docker exec -it name_container /bin/sh
```



